### ISSUE TITLE
Model continually yields 0 buys and 0 sells

### ISSUE THREAD

**Issue by ajspencer** [anfederico/Clairvoyant#11]
Thank you for the great work on the project! I'm really excited to test it out. 

I downloaded data from five stocks through Yahoo finance and am attempting to use the model on them, but it only returns 0 buys and 0 sells no matter how I adjust the parameters. 

I've attached my code, the output I see, and a sample of my data (abridged). I've been experimenting with different buy and sell thresholds trying to force it to sell, but I haven't been able to. 

Code:
```
   1  from clairvoyant import Backtest
   2  from pandas import read_csv
   3 
   4 # Testing performance on a single stock
   5 
   6 variables = ["Close", "Volume"]
   7 trainStart = '2012-05-21'       # Start of training period
   8 trainEnd   = '2015-06-15'       # End of training period
   9 testStart  = '2015-06-16'       # Start of testing period
  10 testEnd    = '2017-02-9'       # End of testing period
  11 buyThreshold  = 0.1            # Confidence threshold for predicting buy (default = 0.65)
  12 sellThreshold = 0.1            # Confidence threshold for predicting sell (default = 0.65)
  13 C = 1                           # Penalty parameter (default = 1)
  14 gamma = 10                      # Kernel coefficient (default = 10)
  15 continuedTraining = False       # Continue training during testing period? (default = false)
  16 
  17 backtest = Backtest(variables, trainStart, trainEnd, testStart, testEnd)
  18 
  19 # Testing performance across multiple stocks
  20 
  21 stocks = ["msft2", "fb2", "appl2", "amzn2", "goog2"]
  22 
  23 for stock in stocks:
  24     data = read_csv('Stocks/%s.csv' % stock)
  25     data = data.round(3)
  26     backtest.stocks.append(stock)
  27     for i in range(0,10):
  28         backtest.runModel(data)
  29 
  30 backtest.displayConditions()
  31 backtest.displayStats()
```
Output:
```

Conditions
X1: Close
X2: Volume
Buy Threshold: 65.0%
Sell Threshold: 65.0%
C: 1
gamma: 10
Continued Training: False
Stats
Stock(s):
msft2 | Training: 05/21/2012-06/15/2015 Testing: 06/16/2015-02/09/2017
fb2 | Training: 05/21/2012-06/15/2015 Testing: 06/16/2015-02/09/2017
appl2 | Training: 05/21/2012-06/15/2015 Testing: 06/16/2015-02/09/2017
amzn2 | Training: 05/21/2012-06/15/2015 Testing: 06/16/2015-02/09/2017
goog2 | Training: 05/21/2012-06/15/2015 Testing: 06/16/2015-02/09/2017

Total Buys: 0
Buy Accuracy: 0.0%
Total Sells: 0
Sell Accuracy: 0.0%
```
Sample data:
```
Date,Open,High,Low,Close,Volume,Adj Close
    02/10/2012,183.419998,187.630005,182.520004,185.539993,5797100,185.539993
    02/13/2012,187.169998,192.50,185.679993,191.589996,6071400,191.589996
    02/14/2012,191.080002,193.570007,186.100006,191.300003,9527100,191.300003
    02/15/2012,191.289993,191.539993,183.259995,184.470001,7794400,184.470001
    02/16/2012,177.789993,181.679993,175.139999,179.929993,12563800,179.929993
    02/17/2012,180.089996,183.410004,179.360001,182.50,7418100,182.50
```

**Comment by anfederico** [comment]
Hey thanks for the nice comments. So first thing I should point out is in your output, your buy/sell thresholds are at default (65%). This may be a high confidence threshold if your data is not very predictable, and it's certainly believable that you'll get 0 buy/sell signals if that is the case.  

Now, it looks like you were trying to change the thresholds to 10% which is a good way to debug. Thing is, you didn't actually change the parameters when you called the Backtest object. Change line 17 to:

backtest = Backtest(variables, trainStart, trainEnd, testStart, testEnd, buyThreshold = 0.1, sellThreshold = 0.1)

If that doesn't work, come back.

**Comment by ajspencer** [comment]
@anfederico thank you for the reply!

I changed the buy and sell thresholds to .1 and .1 and ran the model again. I got 20850 total buys, 0 sells, and 51.89% buy accuracy. Do you have suggested values for the buy and sell thresholds, or a technique to determine the optimal ones?

**Comment by anfederico** [comment]
So the issue isn't the parameters, it's your data. I am 100% certain the 'Close' and 'Volume' are not a combination of financial indicators predictive of stock movement. And I'm sure you'll see with the visualization method that SVC is not going to find many hotspots for buying/selling. 

I'd recommend doing some research about more advanced indicators or try getting your hands on some sentiment data, which is what I personally find to be the best kind of data for predicting short term changes in the market.

**Comment by ajspencer** [comment]
@anfederico thanks for the heads up! I'll close the issue.
