### ISSUE TITLE
Stocks.csv format

### ISSUE THREAD

**Issue by BasharAG** [anfederico/Clairvoyant#12]
I created a Stocks.csv file for the first test code you had on the readme page, but I can't figure out the format required for the script to work. Do you have a template?

**Comment by anfederico** [comment]
This is what your format should look like for a single stock.

Date,Open,High,Low,Close,Volume,SSO,SCC
03/01/2013,27.72,27.98,27.52,27.95,34851872,65.7894736842,-0.121
03/04/2013,27.85,28.15,27.7,28.15,38167504,75.9450171821,0.832
03/05/2013,28.29,28.54,28.16,28.35,41437136,84.9230769231,0.151
03/06/2013,28.21,28.23,27.78,28.09,51448912,80.7799442897,-0.689
03/07/2013,28.11,28.28,28.005,28.14,29197632,73.5368956743,-0.821
