### ISSUE TITLE
Date format error

### ISSUE THREAD

**Issue by BasharAG** [anfederico/Clairvoyant#14]
I got new info and entered it in the SBUX.csv file, but I keep getting this every time I run it:

```
File "test.py", line 17, in <module>
    backtest = Backtest(variables, trainStart, trainEnd, testStart, testEnd)
  File "/root/clair/clairvoyant/Backtest.py", line 47, in __init__
    self.trainEnd           = to_datetime(trainEnd)
  File "/usr/local/lib/python2.7/dist-packages/pandas/util/decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/tools.py", line 430, in to_datetime
    return _convert_listlike(np.array([arg]), box, format)[0]
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/tools.py", line 413, in _convert_listlike
    raise e
ValueError: month must be in 1..12
```

I changed the date format and everything. Here is what my data looks like:

> 
> Date,Open,High,Low,Close,Volume
> 2-1-2015,12.33,12.84,11.87,12.67,221293
> 5-1-2015,12.57,13.34,12.19,13.02,335037
> 6-1-2015,13,13.45,12.29,12.8,369810
> 7-1-2015,12.95,13.23,12.05,13.1,561895
> 8-1-2015,13.19,14.07,12.91,14.05,539694
> 9-1-2015,13.98,14.2,13.39,13.61,626020
> 12-1-2015,13.7,14.25,13.39,13.52,176644
> 13-1-2015,13.7,14.17,12.94,13.21,457432
> 14-1-2015,13.06,14.18,12.1,14.17,310948
> 15-1-2015,14.19,14.5,13.41,13.44,486042
> 16-1-2015,13.38,13.87,13.21,13.54,283274

**Comment by anfederico** [comment]
Your date format needs to start with the month, not the day. 

Ex. mm-dd-yyyy

**Comment by BasharAG** [comment]
Tried it with both approaches, still doesn't work
