### ISSUE TITLE
ImportError: No module named 'backtester'

### ISSUE THREAD

**Issue by JafferWilson** [anfederico/Clairvoyant#19]
I m trying to run the example from your instructions. I am getting the error:  
`ImportError: No module named 'backtester'`

Kindly, let me know what is the cause of this?

**Comment by anfederico** [comment]
What Python version are you using?

**Comment by JafferWilson** [comment]
I am using Python 3.5
I tried it already.  Not working.

**Comment by JafferWilson** [comment]
Check this image:  

![capture](https://user-images.githubusercontent.com/13446197/30696594-d0e37edc-9ef9-11e7-8741-b9021ef29c3e.PNG)

**Comment by anfederico** [comment]
Not sure what happened but this should work, sorry for the confusion.

`from clairvoyant.engine import Backtest`

**Comment by JafferWilson** [comment]
No worries... Let me check it.

**Comment by JafferWilson** [comment]
It worked thank you for help.

**Comment by santosh1383** [comment]
What did you do? I am still getting an error: "NameError: name 'backtester' is not defined" or "AttributeError: 'Backtest' object has no attribute 'Simulation'"  or " AttributeError: type object 'Backtest' has no attribute 'Simulation'"
