### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by cizmek777** [anfederico/Clairvoyant#24]
Hi,
I  use the `data.csv` and following indicators in the test code, but get above error.
`features  = ["X1", "X2"]`

here is the data.head():
      
>    date   open    high     low  close    volume      X1     X2
> 0  4/15/16  60.24  60.625  60.010  60.51   5965310  59.959  0.268
> 1  4/18/16  60.69  61.070  60.355  60.89   7228573  60.048  0.009
> 2  4/19/16  61.16  61.250  60.480  60.90   7283570  60.129  0.505
> 3  4/20/16  61.04  61.430  60.850  60.90   5558770  60.203  1.190
> 4  4/21/16  60.90  61.100  60.480  60.64  12799083  60.244  2.586

**Comment by andrushkin** [comment]
Same problem here

**Comment by anfederico** [comment]
The test data only has 322 rows, therefore you need to change this part of the example code.

```
trainStart = 0               # Start of training period
trainEnd   = 200             # End of training period
testStart  = 201             # Start of testing period
testEnd    = 321             # End of testing period
```
