### ISSUE TITLE
SyntaxError: invalid syntax : "self.svc = SVC(**kwargs, probability=True)"

### ISSUE THREAD

**Issue by arambula1980** [anfederico/Clairvoyant#25]
First of all, let me start by thanking you very much for all your hard work and dedication. Your work is truly magnificent. 

I am trying to run the example from your instructions. I am getting the error:

File "C:\Python27\lib\site-packages\clairvoyant\model.py", line 22
    self.svc = SVC(**kwargs, probability=True)

SyntaxError: invalid syntax

What could be the cause of this error ?

I am running Python 2.7.15

**Comment by anfederico** [comment]
Do you have these dependencies installed?

```
bokeh>=0.12.4
matplotlib>=2.0.0
numpy>=1.11.3
pandas>=0.19.2
scikit-learn>=0.18.1
```

Specifically scikit-learn?

**Comment by arambula1980** [comment]
Hi Federico,

Thank you very much for coming back so quick. Yes, all the above dependencies have been met. I have the latest versions.

![image](https://user-images.githubusercontent.com/19308041/44348525-479bab00-a460-11e8-84c0-ab02556a6740.png)

**Comment by anfederico** [comment]
Hmmm a lot of these packages are dropping Python 2 support by December of this year. Can you try in Python 3?

**Comment by arambula1980** [comment]
Thanks for looking into it . This is working now .
