### ISSUE TITLE
KeyError: 'EMA'

### ISSUE THREAD

**Issue by codylabelle** [anfederico/Clairvoyant#27]
Hi! Thank you for uploading this project.

I am having an issue running Backtest using the code in your README.md file. Using all of your original code and your example data, I receive the following error (I've edited out the traceback parts):

```
TypeError: 'str' object cannot be interpreted as an integer

  File "pandas\_libs\index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA'
```
Am I setting up the features incorrectly or do you know why I might be receiving this error? I am running python 3.6.4 and all of the dependencies are installed and up to date, as per the versions listed in the SyntaxError issue posted.

**Comment by anfederico** [comment]
Example data has feature columns called "X1" and "X2". I should make that more clear.

**Comment by qg0** [comment]
I've deleted the "X1" and "X2" parameters. I have the "**KeyError: 'EMA'**".

```python
import pandas as pd
from clairvoyant.engine import Backtest
```


```python
features  = ["EMA", "SSO"]   # Financial indicators of choice
trainStart = 0               # Start of training period
trainEnd   = 700             # End of training period
testStart  = 701             # Start of testing period
testEnd    = 1000            # End of testing period
buyThreshold  = 0.65         # Confidence threshold for predicting buy (default = 0.65)
sellThreshold = 0.65         # Confidence threshold for predicting sell (default = 0.65)
continuedTraining = False    # Continue training during testing period? (default = false)

# Initialize backtester
backtest = Backtest(features, trainStart, trainEnd, testStart, testEnd, buyThreshold, sellThreshold, continuedTraining)

# A little bit of pre-processing
data = pd.read_csv("~/projects/harmonic/data/data.csv", date_parser=['date'])
data = data[['date','open','high','low','close','volume']]
data = data.round(3)
data.tail()
```




<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>317</th>
      <td>7/19/17</td>
      <td>58.150</td>
      <td>58.41</td>
      <td>57.90</td>
      <td>58.11</td>
      <td>8203557</td>
    </tr>
    <tr>
      <th>318</th>
      <td>7/20/17</td>
      <td>58.410</td>
      <td>58.84</td>
      <td>58.00</td>
      <td>58.03</td>
      <td>10546701</td>
    </tr>
    <tr>
      <th>319</th>
      <td>7/21/17</td>
      <td>57.920</td>
      <td>58.26</td>
      <td>57.83</td>
      <td>57.98</td>
      <td>6717235</td>
    </tr>
    <tr>
      <th>320</th>
      <td>7/24/17</td>
      <td>58.000</td>
      <td>58.25</td>
      <td>57.93</td>
      <td>58.02</td>
      <td>7442589</td>
    </tr>
    <tr>
      <th>321</th>
      <td>7/25/17</td>
      <td>58.215</td>
      <td>58.84</td>
      <td>57.98</td>
      <td>58.74</td>
      <td>4314841</td>
    </tr>
  </tbody>
</table>
</div>




```python
# Start backtesting and optionally modify SVC parameters
# Available paramaters can be found at: http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
backtest.start(data, kernel='rbf', C=1, gamma=10)
backtest.conditions()
backtest.statistics()
backtest.visualize('SBUX')
```


    ---------------------------------------------------------------------------

    KeyError                                  Traceback (most recent call last)

    ~/bin/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
       2888             try:
    -> 2889                 return self._engine.get_loc(casted_key)
       2890             except KeyError as err:


    pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()


    pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()


    pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()


    pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()


    KeyError: 'EMA'

    
    The above exception was the direct cause of the following exception:


    KeyError                                  Traceback (most recent call last)

    <ipython-input-7-5ea2363c2602> in <module>
          1 # Start backtesting and optionally modify SVC parameters
          2 # Available paramaters can be found at: http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
    ----> 3 backtest.start(data, kernel='rbf', C=1, gamma=10)
          4 backtest.conditions()
          5 backtest.statistics()


    ~/bin/anaconda3/lib/python3.7/site-packages/clairvoyant/engine.py in start(self, data, **kwargs)
        195 
        196     def start(self, data, **kwargs):
    --> 197         Engine.start(self, data, **kwargs)
        198 
        199     def buyStats(self):


    ~/bin/anaconda3/lib/python3.7/site-packages/clairvoyant/engine.py in start(self, data, capital, logic, simulation, **kwargs)
         50         for i in range(self.trainStr, self.trainEnd+1):
         51 
    ---> 52             Xs = [data.iloc[i][var] for var in self.features]
         53             X.append(Xs)
         54 


    ~/bin/anaconda3/lib/python3.7/site-packages/clairvoyant/engine.py in <listcomp>(.0)
         50         for i in range(self.trainStr, self.trainEnd+1):
         51 
    ---> 52             Xs = [data.iloc[i][var] for var in self.features]
         53             X.append(Xs)
         54 


    ~/bin/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
        880 
        881         elif key_is_scalar:
    --> 882             return self._get_value(key)
        883 
        884         if (


    ~/bin/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in _get_value(self, label, takeable)
        989 
        990         # Similar to Index.get_value, but we do not fall back to positional
    --> 991         loc = self.index.get_loc(label)
        992         return self.index._get_values_for_loc(self, loc, label)
        993 


    ~/bin/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
       2889                 return self._engine.get_loc(casted_key)
       2890             except KeyError as err:
    -> 2891                 raise KeyError(key) from err
       2892 
       2893         if tolerance is not None:


    KeyError: 'EMA'
