### ISSUE TITLE
Code seems incorrect

### ISSUE THREAD

**Issue by mukesh12z** [anfederico/Clairvoyant#31]
in Engine.start for below code:

Xs = [ data.iloc[i][var] for var in self.features ]

features are mentioned as ["EMA","SSO"] # i assume we need to map them to X1, X2.
iloc takes indexes as integers, it will not work as i.e; data.iloc[0]["EMA"] .

**Comment by anfederico** [comment]
The example data is not meant to go with the README tutorial. Therefore change EMA/SSO to X1/X2 respectively if you are using the example data.
