### ISSUE TITLE
Getting Clairvoyant  to work

### ISSUE THREAD

**Issue by brahimelron** [anfederico/Clairvoyant#6]
I am having the following issue in getting the Clairvoyant project, that identifies and monitors social/historical cues for short term stock movement, to run successfully:
The file hashtable_class_helper.pxl could not be opened.
Here is the exception generated:
Exception "unhandled KeyError"
'SSO'
File: pandas/src/hashtable_class_helper.pxi, Line: 740

I think it might have something to do with the fact that this is a cython-based project and I'm wanting to implement in Python 2.7x in Ubuntu 16.04

Any help would be appreciated.

**Comment by anfederico** [comment]
I think the issue is your data file. "SSO" is an indicator I was using as an example in the readme, therefore you shouldn't be passing "SSO" as a key unless your own data also includes a variable called "SSO".

**Comment by brahimelron** [comment]
Got it. Thanks
