### ISSUE TITLE
Files with sample data

### ISSUE THREAD

**Issue by mglowacki100** [anfederico/Clairvoyant#9]
It would be great to have files with sample data included in repo. 
It doesn't have to be real data, but it would be helpful to making Clairvoyant up and running with my own data (e.g. I don't know if it should be minute data, or daily OHLCV).

**Comment by anfederico** [comment]
Should be daily data. I'll upload some sample datasets!

**Comment by ajspencer** [comment]
@anfederico thanks for the awesome work! Did you ever get around to adding sample data sets? I couldn't find any in the repo.
